from ..auto_doc import TrackedTable


class HospitalN(TrackedTable):
    name = 'hospital_n'

    def build(self, cursor=None):
        if not cursor:
            cursor = self.get_cursor()

        cursor.execute(
            "CREATE FUNCTION pg_temp.TO_NUMERIC_OR_NULL(inpt TEXT) RETURNS NUMERIC AS "
                "$$ "
                    "SELECT CASE "
                        "WHEN inpt ~ '^\\d+$' "
                            "THEN inpt::numeric "
                        "ELSE "
                            "NULL "
                    "END "
                "$$ LANGUAGE SQL;"
        )

        cursor.execute(
            "CREATE FUNCTION pg_temp.TO_TIME_OR_NULL(inpt TEXT) RETURNS TIME AS "
                "$$ "
                    "SELECT CASE "
                        "WHEN inpt ~ '^\\d{2}:\\d{2}$' "
                            "THEN TO_TIMESTAMP(inpt, 'HH24:MI')::time "
                        "ELSE "
                            "NULL "
                    "END "
                "$$ LANGUAGE SQL"
        )

        cursor.execute(
            "CREATE TABLE hospital_n AS SELECT "
                "TO_DATE(import_hosp_n_addate, 'YYYY-MM-DD') as hospital_n_addate, "
                "import_hosp_n_admit, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_adtime) as hospital_n_adtime, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_alcdays) as hospital_n_alcdays, "
                "import_hosp_n_ambulanc, "
                "import_hosp_n_ana1, "
                "import_hosp_n_ana2, "
                "import_hosp_n_ana3, "
                "import_hosp_n_ana4, "
                "import_hosp_n_ana5, "
                "import_hosp_n_ana6, "
                "import_hosp_n_ana7, "
                "import_hosp_n_ana8, "
                "import_hosp_n_ana9, "
                "import_hosp_n_ana10, "
                "import_hosp_n_ana11, "
                "import_hosp_n_ana12, "
                "import_hosp_n_ana13, "
                "import_hosp_n_ana14, "
                "import_hosp_n_ana15, "
                "import_hosp_n_ana16, "
                "import_hosp_n_ana17, "
                "import_hosp_n_ana18, "
                "import_hosp_n_ana19, "
                "import_hosp_n_ana20, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas1) as hospital_n_e_anas1, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas2) as hospital_n_e_anas2, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas3) as hospital_n_e_anas3, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas4) as hospital_n_e_anas4, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas5) as hospital_n_e_anas5, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas6) as hospital_n_e_anas6, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas7) as hospital_n_e_anas7, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas8) as hospital_n_e_anas8, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas9) as hospital_n_e_anas9, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas10) as hospital_n_e_anas10, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas11) as hospital_n_e_anas11, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas12) as hospital_n_e_anas12, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas13) as hospital_n_e_anas13, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas14) as hospital_n_e_anas14, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas15) as hospital_n_e_anas15, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas16) as hospital_n_e_anas16, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas17) as hospital_n_e_anas17, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas18) as hospital_n_e_anas18, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas19) as hospital_n_e_anas19, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_e_anas20) as hospital_n_e_anas20, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_ar_days) as hospital_n_ar_days, "
                "import_hosp_n_bclvlfrm, "
                "import_hosp_n_bclvlto, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_birthwt) as hospital_n_birthwt, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_burndays) as hospital_n_burndays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_carddays) as hospital_n_carddays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_cbddays) as hospital_n_cbddays, "
                "import_hosp_n_ccindctr, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_ccudays) as hospital_n_ccudays, "
                "import_hosp_n_cds00t98, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_combdays) as hospital_n_combdays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_combsdudays) as hospital_n_combsdudays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_days1) as hospital_n_days1, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_days2) as hospital_n_days2, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_days3) as hospital_n_days3, "
                "import_hosp_n_diagclus1, "
                "import_hosp_n_diagclus2, "
                "import_hosp_n_diagclus3, "
                "import_hosp_n_diagclus4, "
                "import_hosp_n_diagclus5, "
                "import_hosp_n_diagclus6, "
                "import_hosp_n_diagclus7, "
                "import_hosp_n_diagclus8, "
                "import_hosp_n_diagclus9, "
                "import_hosp_n_diagclus10, "
                "import_hosp_n_diagclus11, "
                "import_hosp_n_diagclus12, "
                "import_hosp_n_diagclus13, "
                "import_hosp_n_diagclus14, "
                "import_hosp_n_diagclus15, "
                "import_hosp_n_diagclus16, "
                "import_hosp_n_diagclus17, "
                "import_hosp_n_diagclus18, "
                "import_hosp_n_diagclus19, "
                "import_hosp_n_diagclus20, "
                "import_hosp_n_diagclus21, "
                "import_hosp_n_diagclus22, "
                "import_hosp_n_diagclus23, "
                "import_hosp_n_diagclus24, "
                "import_hosp_n_diagclus25, "
                "import_hosp_n_diagx1, "
                "import_hosp_n_diagx2, "
                "import_hosp_n_diagx3, "
                "import_hosp_n_diagx4, "
                "import_hosp_n_diagx5, "
                "import_hosp_n_diagx6, "
                "import_hosp_n_diagx7, "
                "import_hosp_n_diagx8, "
                "import_hosp_n_diagx9, "
                "import_hosp_n_diagx10, "
                "import_hosp_n_diagx11, "
                "import_hosp_n_diagx12, "
                "import_hosp_n_diagx13, "
                "import_hosp_n_diagx14, "
                "import_hosp_n_diagx15, "
                "import_hosp_n_diagx16, "
                "import_hosp_n_diagx17, "
                "import_hosp_n_diagx18, "
                "import_hosp_n_diagx19, "
                "import_hosp_n_diagx20, "
                "import_hosp_n_diagx21, "
                "import_hosp_n_diagx22, "
                "import_hosp_n_diagx23, "
                "import_hosp_n_diagx24, "
                "import_hosp_n_diagx25, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_doc_spec) as hospital_n_doc_spec, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_dsc) as hospital_n_dsc, "
                "import_hosp_n_dtypx1, "
                "import_hosp_n_dtypx2, "
                "import_hosp_n_dtypx3, "
                "import_hosp_n_dtypx4, "
                "import_hosp_n_dtypx5, "
                "import_hosp_n_dtypx6, "
                "import_hosp_n_dtypx7, "
                "import_hosp_n_dtypx8, "
                "import_hosp_n_dtypx9, "
                "import_hosp_n_dtypx10, "
                "import_hosp_n_dtypx11, "
                "import_hosp_n_dtypx12, "
                "import_hosp_n_dtypx13, "
                "import_hosp_n_dtypx14, "
                "import_hosp_n_dtypx15, "
                "import_hosp_n_dtypx16, "
                "import_hosp_n_dtypx17, "
                "import_hosp_n_dtypx18, "
                "import_hosp_n_dtypx19, "
                "import_hosp_n_dtypx20, "
                "import_hosp_n_dtypx21, "
                "import_hosp_n_dtypx22, "
                "import_hosp_n_dtypx23, "
                "import_hosp_n_dtypx24, "
                "import_hosp_n_dtypx25, "
                "import_hosp_n_ecodex1, "
                "TO_DATE(import_hosp_n_edregdate, 'YYYY-MM-DD') as hospital_n_edregdate, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_edregtime) as hospital_n_edregtime, "
                "import_hosp_n_entry, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric1) as hospital_n_epnumeric1, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric2) as hospital_n_epnumeric2, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric3) as hospital_n_epnumeric3, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric4) as hospital_n_epnumeric4, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric5) as hospital_n_epnumeric5, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric6) as hospital_n_epnumeric6, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric7) as hospital_n_epnumeric7, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric8) as hospital_n_epnumeric8, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric9) as hospital_n_epnumeric9, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric10) as hospital_n_epnumeric10, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric11) as hospital_n_epnumeric11, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric12) as hospital_n_epnumeric12, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric13) as hospital_n_epnumeric13, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric14) as hospital_n_epnumeric14, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric15) as hospital_n_epnumeric15, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric16) as hospital_n_epnumeric16, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric17) as hospital_n_epnumeric17, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric18) as hospital_n_epnumeric18, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric19) as hospital_n_epnumeric19, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epnumeric20) as hospital_n_epnumeric20, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq1) as hospital_n_epseq1, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq2) as hospital_n_epseq2, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq3) as hospital_n_epseq3, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq4) as hospital_n_epseq4, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq5) as hospital_n_epseq5, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq6) as hospital_n_epseq6, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq7) as hospital_n_epseq7, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq8) as hospital_n_epseq8, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq9) as hospital_n_epseq9, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq10) as hospital_n_epseq10, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq11) as hospital_n_epseq11, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq12) as hospital_n_epseq12, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq13) as hospital_n_epseq13, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq14) as hospital_n_epseq14, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq15) as hospital_n_epseq15, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq16) as hospital_n_epseq16, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq17) as hospital_n_epseq17, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq18) as hospital_n_epseq18, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq19) as hospital_n_epseq19, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_epseq20) as hospital_n_epseq20, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_gestad) as hospital_n_gestad, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_gestdel) as hospital_n_gestdel, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_gestdis) as hospital_n_gestdis, "
                "import_hosp_n_hcnprov, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_hosp) as hospital_n_hosp, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_hospfrom) as hospital_n_hospfrom, "
                "import_hosp_n_hospprov, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_hospto) as hospital_n_hospto, "
                "import_hosp_n_icode1, "
                "import_hosp_n_icode2, "
                "import_hosp_n_icode3, "
                "import_hosp_n_icode4, "
                "import_hosp_n_icode5, "
                "import_hosp_n_icode6, "
                "import_hosp_n_icode7, "
                "import_hosp_n_icode8, "
                "import_hosp_n_icode9, "
                "import_hosp_n_icode10, "
                "import_hosp_n_icode11, "
                "import_hosp_n_icode12, "
                "import_hosp_n_icode13, "
                "import_hosp_n_icode14, "
                "import_hosp_n_icode15, "
                "import_hosp_n_icode16, "
                "import_hosp_n_icode17, "
                "import_hosp_n_icode18, "
                "import_hosp_n_icode19, "
                "import_hosp_n_icode20, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_icudays) as hospital_n_icudays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur1) as hospital_n_idur1, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur2) as hospital_n_idur2, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur3) as hospital_n_idur3, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur4) as hospital_n_idur4, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur5) as hospital_n_idur5, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur6) as hospital_n_idur6, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur7) as hospital_n_idur7, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur8) as hospital_n_idur8, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur9) as hospital_n_idur9, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur10) as hospital_n_idur10, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur11) as hospital_n_idur11, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur12) as hospital_n_idur12, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur13) as hospital_n_idur13, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur14) as hospital_n_idur14, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur15) as hospital_n_idur15, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur16) as hospital_n_idur16, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur17) as hospital_n_idur17, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur18) as hospital_n_idur18, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur19) as hospital_n_idur19, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_idur20) as hospital_n_idur20, "
                "TO_DATE(import_hosp_n_ienddate1, 'YYYY-MM-DD') as hospital_n_ienddate1, "
                "TO_DATE(import_hosp_n_ienddate2, 'YYYY-MM-DD') as hospital_n_ienddate2, "
                "TO_DATE(import_hosp_n_ienddate3, 'YYYY-MM-DD') as hospital_n_ienddate3, "
                "TO_DATE(import_hosp_n_ienddate4, 'YYYY-MM-DD') as hospital_n_ienddate4, "
                "TO_DATE(import_hosp_n_ienddate5, 'YYYY-MM-DD') as hospital_n_ienddate5, "
                "TO_DATE(import_hosp_n_ienddate6, 'YYYY-MM-DD') as hospital_n_ienddate6, "
                "TO_DATE(import_hosp_n_ienddate7, 'YYYY-MM-DD') as hospital_n_ienddate7, "
                "TO_DATE(import_hosp_n_ienddate8, 'YYYY-MM-DD') as hospital_n_ienddate8, "
                "TO_DATE(import_hosp_n_ienddate9, 'YYYY-MM-DD') as hospital_n_ienddate9, "
                "TO_DATE(import_hosp_n_ienddate10, 'YYYY-MM-DD') as hospital_n_ienddate10, "
                "TO_DATE(import_hosp_n_ienddate11, 'YYYY-MM-DD') as hospital_n_ienddate11, "
                "TO_DATE(import_hosp_n_ienddate12, 'YYYY-MM-DD') as hospital_n_ienddate12, "
                "TO_DATE(import_hosp_n_ienddate13, 'YYYY-MM-DD') as hospital_n_ienddate13, "
                "TO_DATE(import_hosp_n_ienddate14, 'YYYY-MM-DD') as hospital_n_ienddate14, "
                "TO_DATE(import_hosp_n_ienddate15, 'YYYY-MM-DD') as hospital_n_ienddate15, "
                "TO_DATE(import_hosp_n_ienddate16, 'YYYY-MM-DD') as hospital_n_ienddate16, "
                "TO_DATE(import_hosp_n_ienddate17, 'YYYY-MM-DD') as hospital_n_ienddate17, "
                "TO_DATE(import_hosp_n_ienddate18, 'YYYY-MM-DD') as hospital_n_ienddate18, "
                "TO_DATE(import_hosp_n_ienddate19, 'YYYY-MM-DD') as hospital_n_ienddate19, "
                "TO_DATE(import_hosp_n_ienddate20, 'YYYY-MM-DD') as hospital_n_ienddate20, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime1) as hospital_n_iendtime1, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime2) as hospital_n_iendtime2, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime3) as hospital_n_iendtime3, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime4) as hospital_n_iendtime4, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime5) as hospital_n_iendtime5, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime6) as hospital_n_iendtime6, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime7) as hospital_n_iendtime7, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime8) as hospital_n_iendtime8, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime9) as hospital_n_iendtime9, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime10) as hospital_n_iendtime10, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime11) as hospital_n_iendtime11, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime12) as hospital_n_iendtime12, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime13) as hospital_n_iendtime13, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime14) as hospital_n_iendtime14, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime15) as hospital_n_iendtime15, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime16) as hospital_n_iendtime16, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime17) as hospital_n_iendtime17, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime18) as hospital_n_iendtime18, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime19) as hospital_n_iendtime19, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_iendtime20) as hospital_n_iendtime20, "
                "import_hosp_n_iext1, "
                "import_hosp_n_iext2, "
                "import_hosp_n_iext3, "
                "import_hosp_n_iext4, "
                "import_hosp_n_iext5, "
                "import_hosp_n_iext6, "
                "import_hosp_n_iext7, "
                "import_hosp_n_iext8, "
                "import_hosp_n_iext9, "
                "import_hosp_n_iext10, "
                "import_hosp_n_iext11, "
                "import_hosp_n_iext12, "
                "import_hosp_n_iext13, "
                "import_hosp_n_iext14, "
                "import_hosp_n_iext15, "
                "import_hosp_n_iext16, "
                "import_hosp_n_iext17, "
                "import_hosp_n_iext18, "
                "import_hosp_n_iext19, "
                "import_hosp_n_iext20, "
                "import_hosp_n_injplace, "
                "import_hosp_n_iooh1, "
                "import_hosp_n_iooh2, "
                "import_hosp_n_iooh3, "
                "import_hosp_n_iooh4, "
                "import_hosp_n_iooh5, "
                "import_hosp_n_iooh6, "
                "import_hosp_n_iooh7, "
                "import_hosp_n_iooh8, "
                "import_hosp_n_iooh9, "
                "import_hosp_n_iooh10, "
                "import_hosp_n_iooh11, "
                "import_hosp_n_iooh12, "
                "import_hosp_n_iooh13, "
                "import_hosp_n_iooh14, "
                "import_hosp_n_iooh15, "
                "import_hosp_n_iooh16, "
                "import_hosp_n_iooh17, "
                "import_hosp_n_iooh18, "
                "import_hosp_n_iooh19, "
                "import_hosp_n_iooh20, "
                "import_hosp_n_ioohnm1, "
                "import_hosp_n_ioohnm2, "
                "import_hosp_n_ioohnm3, "
                "import_hosp_n_ioohnm4, "
                "import_hosp_n_ioohnm5, "
                "import_hosp_n_ioohnm6, "
                "import_hosp_n_ioohnm7, "
                "import_hosp_n_ioohnm8, "
                "import_hosp_n_ioohnm9, "
                "import_hosp_n_ioohnm10, "
                "import_hosp_n_ioohnm11, "
                "import_hosp_n_ioohnm12, "
                "import_hosp_n_ioohnm13, "
                "import_hosp_n_ioohnm14, "
                "import_hosp_n_ioohnm15, "
                "import_hosp_n_ioohnm16, "
                "import_hosp_n_ioohnm17, "
                "import_hosp_n_ioohnm18, "
                "import_hosp_n_ioohnm19, "
                "import_hosp_n_ioohnm20, "
                "import_hosp_n_ipreadmit1, "
                "import_hosp_n_ipreadmit2, "
                "import_hosp_n_ipreadmit3, "
                "import_hosp_n_ipreadmit4, "
                "import_hosp_n_ipreadmit5, "
                "import_hosp_n_ipreadmit6, "
                "import_hosp_n_ipreadmit7, "
                "import_hosp_n_ipreadmit8, "
                "import_hosp_n_ipreadmit9, "
                "import_hosp_n_ipreadmit10, "
                "import_hosp_n_ipreadmit11, "
                "import_hosp_n_ipreadmit12, "
                "import_hosp_n_ipreadmit13, "
                "import_hosp_n_ipreadmit14, "
                "import_hosp_n_ipreadmit15, "
                "import_hosp_n_ipreadmit16, "
                "import_hosp_n_ipreadmit17, "
                "import_hosp_n_ipreadmit18, "
                "import_hosp_n_ipreadmit19, "
                "import_hosp_n_ipreadmit20, "
                "import_hosp_n_iretrn1, "
                "import_hosp_n_iretrn2, "
                "import_hosp_n_iretrn3, "
                "import_hosp_n_iretrn4, "
                "import_hosp_n_iretrn5, "
                "import_hosp_n_iretrn6, "
                "import_hosp_n_iretrn7, "
                "import_hosp_n_iretrn8, "
                "import_hosp_n_iretrn9, "
                "import_hosp_n_iretrn10, "
                "import_hosp_n_iretrn11, "
                "import_hosp_n_iretrn12, "
                "import_hosp_n_iretrn13, "
                "import_hosp_n_iretrn14, "
                "import_hosp_n_iretrn15, "
                "import_hosp_n_iretrn16, "
                "import_hosp_n_iretrn17, "
                "import_hosp_n_iretrn18, "
                "import_hosp_n_iretrn19, "
                "import_hosp_n_iretrn20, "
                "import_hosp_n_isite1, "
                "import_hosp_n_isite2, "
                "import_hosp_n_isite3, "
                "import_hosp_n_isite4, "
                "import_hosp_n_isite5, "
                "import_hosp_n_isite6, "
                "import_hosp_n_isite7, "
                "import_hosp_n_isite8, "
                "import_hosp_n_isite9, "
                "import_hosp_n_isite10, "
                "import_hosp_n_isite11, "
                "import_hosp_n_isite12, "
                "import_hosp_n_isite13, "
                "import_hosp_n_isite14, "
                "import_hosp_n_isite15, "
                "import_hosp_n_isite16, "
                "import_hosp_n_isite17, "
                "import_hosp_n_isite18, "
                "import_hosp_n_isite19, "
                "import_hosp_n_isite20, "
                "import_hosp_n_isl, "
                "TO_DATE(import_hosp_n_istartdate1, 'YYYY-MM-DD') as hospital_n_istartdate1, "
                "TO_DATE(import_hosp_n_istartdate2, 'YYYY-MM-DD') as hospital_n_istartdate2, "
                "TO_DATE(import_hosp_n_istartdate3, 'YYYY-MM-DD') as hospital_n_istartdate3, "
                "TO_DATE(import_hosp_n_istartdate4, 'YYYY-MM-DD') as hospital_n_istartdate4, "
                "TO_DATE(import_hosp_n_istartdate5, 'YYYY-MM-DD') as hospital_n_istartdate5, "
                "TO_DATE(import_hosp_n_istartdate6, 'YYYY-MM-DD') as hospital_n_istartdate6, "
                "TO_DATE(import_hosp_n_istartdate7, 'YYYY-MM-DD') as hospital_n_istartdate7, "
                "TO_DATE(import_hosp_n_istartdate8, 'YYYY-MM-DD') as hospital_n_istartdate8, "
                "TO_DATE(import_hosp_n_istartdate9, 'YYYY-MM-DD') as hospital_n_istartdate9, "
                "TO_DATE(import_hosp_n_istartdate10, 'YYYY-MM-DD') as hospital_n_istartdate10, "
                "TO_DATE(import_hosp_n_istartdate11, 'YYYY-MM-DD') as hospital_n_istartdate11, "
                "TO_DATE(import_hosp_n_istartdate12, 'YYYY-MM-DD') as hospital_n_istartdate12, "
                "TO_DATE(import_hosp_n_istartdate13, 'YYYY-MM-DD') as hospital_n_istartdate13, "
                "TO_DATE(import_hosp_n_istartdate14, 'YYYY-MM-DD') as hospital_n_istartdate14, "
                "TO_DATE(import_hosp_n_istartdate15, 'YYYY-MM-DD') as hospital_n_istartdate15, "
                "TO_DATE(import_hosp_n_istartdate16, 'YYYY-MM-DD') as hospital_n_istartdate16, "
                "TO_DATE(import_hosp_n_istartdate17, 'YYYY-MM-DD') as hospital_n_istartdate17, "
                "TO_DATE(import_hosp_n_istartdate18, 'YYYY-MM-DD') as hospital_n_istartdate18, "
                "TO_DATE(import_hosp_n_istartdate19, 'YYYY-MM-DD') as hospital_n_istartdate19, "
                "TO_DATE(import_hosp_n_istartdate20, 'YYYY-MM-DD') as hospital_n_istartdate20, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime1) as hospital_n_istarttime1, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime2) as hospital_n_istarttime2, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime3) as hospital_n_istarttime3, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime4) as hospital_n_istarttime4, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime5) as hospital_n_istarttime5, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime6) as hospital_n_istarttime6, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime7) as hospital_n_istarttime7, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime8) as hospital_n_istarttime8, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime9) as hospital_n_istarttime9, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime10) as hospital_n_istarttime10, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime11) as hospital_n_istarttime11, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime12) as hospital_n_istarttime12, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime13) as hospital_n_istarttime13, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime14) as hospital_n_istarttime14, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime15) as hospital_n_istarttime15, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime16) as hospital_n_istarttime16, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime17) as hospital_n_istarttime17, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime18) as hospital_n_istarttime18, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime19) as hospital_n_istarttime19, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_istarttime20) as hospital_n_istarttime20, "
                "import_hosp_n_istat1, "
                "import_hosp_n_istat2, "
                "import_hosp_n_istat3, "
                "import_hosp_n_istat4, "
                "import_hosp_n_istat5, "
                "import_hosp_n_istat6, "
                "import_hosp_n_istat7, "
                "import_hosp_n_istat8, "
                "import_hosp_n_istat9, "
                "import_hosp_n_istat10, "
                "import_hosp_n_istat11, "
                "import_hosp_n_istat12, "
                "import_hosp_n_istat13, "
                "import_hosp_n_istat14, "
                "import_hosp_n_istat15, "
                "import_hosp_n_istat16, "
                "import_hosp_n_istat17, "
                "import_hosp_n_istat18, "
                "import_hosp_n_istat19, "
                "import_hosp_n_istat20, "
                "TO_DATE(import_hosp_n_lefterdt, 'YYYY-MM-DD') as hospital_n_lefterdt, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_leftertm) as hospital_n_leftertm, "
                "import_hosp_n_level, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_meddays) as hospital_n_meddays, "
                "import_hosp_n_mhia4, "
                "import_hosp_n_mhia10, "
                "import_hosp_n_mhia20, "
                "import_hosp_n_mhia21, "
                "import_hosp_n_mhiadmit, "
                "import_hosp_n_mhiapol, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_neondays) as hospital_n_neondays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_neurdays) as hospital_n_neurdays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_nicul1days) as hospital_n_nicul1days, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_nicul2days) as hospital_n_nicul2days, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_nicul3days) as hospital_n_nicul3days, "
                "import_hosp_n_oohint1, "
                "import_hosp_n_oohint2, "
                "import_hosp_n_oohint3, "
                "import_hosp_n_oohint4, "
                "import_hosp_n_oohint5, "
                "import_hosp_n_oohint6, "
                "import_hosp_n_oohint7, "
                "import_hosp_n_oohint8, "
                "import_hosp_n_oohint9, "
                "import_hosp_n_oohint10, "
                "import_hosp_n_oohint11, "
                "import_hosp_n_oohint12, "
                "import_hosp_n_oohint13, "
                "import_hosp_n_oohint14, "
                "import_hosp_n_oohint15, "
                "import_hosp_n_oohint16, "
                "import_hosp_n_oohint17, "
                "import_hosp_n_oohint18, "
                "import_hosp_n_oohint19, "
                "import_hosp_n_oohint20, "
                "import_hosp_n_oophosp, "
                "import_hosp_n_opdeath, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_patserv) as hospital_n_patserv, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_pedidays) as hospital_n_pedidays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_priv_hosp) as hospital_n_priv_hosp, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_readmit) as hospital_n_readmit, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_recrdnumeric) as hospital_n_recrdnumeric, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_rehabday) as hospital_n_rehabday, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_respdays) as hospital_n_respdays, "
                "import_hosp_n_respphys, "
                "import_hosp_n_rfp, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_scu1days) as hospital_n_scu1days, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_scu2days) as hospital_n_scu2days, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_scu3days) as hospital_n_scu3days, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_scu4days) as hospital_n_scu4days, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_scu5days) as hospital_n_scu5days, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_scu6days) as hospital_n_scu6days, "
                "import_hosp_n_scudeath, "
                "import_hosp_n_sdsurg, "
                "TO_DATE(import_hosp_n_sepdate, 'YYYY-MM-DD') as hospital_n_sepdate, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_sepdisp) as hospital_n_sepdisp, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_septime) as hospital_n_septime, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_serv1) as hospital_n_serv1, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_serv2) as hospital_n_serv2, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_serv3) as hospital_n_serv3, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_smeddays) as hospital_n_smeddays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv1) as hospital_n_srv1, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv2) as hospital_n_srv2, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv3) as hospital_n_srv3, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv4) as hospital_n_srv4, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv5) as hospital_n_srv5, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv6) as hospital_n_srv6, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv7) as hospital_n_srv7, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv8) as hospital_n_srv8, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv9) as hospital_n_srv9, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv10) as hospital_n_srv10, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv11) as hospital_n_srv11, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv12) as hospital_n_srv12, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv13) as hospital_n_srv13, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv14) as hospital_n_srv14, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv15) as hospital_n_srv15, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv16) as hospital_n_srv16, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv17) as hospital_n_srv17, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv18) as hospital_n_srv18, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv19) as hospital_n_srv19, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_srv20) as hospital_n_srv20, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_ssrgdays) as hospital_n_ssrgdays, "
                "import_hosp_n_surg1, "
                "import_hosp_n_surg2, "
                "import_hosp_n_surg3, "
                "import_hosp_n_surg4, "
                "import_hosp_n_surg5, "
                "import_hosp_n_surg6, "
                "import_hosp_n_surg7, "
                "import_hosp_n_surg8, "
                "import_hosp_n_surg9, "
                "import_hosp_n_surg10, "
                "import_hosp_n_surg11, "
                "import_hosp_n_surg12, "
                "import_hosp_n_surg13, "
                "import_hosp_n_surg14, "
                "import_hosp_n_surg15, "
                "import_hosp_n_surg16, "
                "import_hosp_n_surg17, "
                "import_hosp_n_surg18, "
                "import_hosp_n_surg19, "
                "import_hosp_n_surg20, "
                "import_hosp_n_surgcase2, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_surgdays) as hospital_n_surgdays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_tdays) as hospital_n_tdays, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_traudays) as hospital_n_traudays, "
                "import_hosp_n_trdparty, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_undefday) as hospital_n_undefday, "
                "import_hosp_n_ventdis, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_venthours) as hospital_n_venthours, "
                "import_hosp_n_ventind, "
                "import_hosp_n_dprefx1, "
                "import_hosp_n_dprefx2, "
                "import_hosp_n_dprefx3, "
                "import_hosp_n_dprefx4, "
                "import_hosp_n_dprefx5, "
                "import_hosp_n_dprefx6, "
                "import_hosp_n_dprefx7, "
                "import_hosp_n_dprefx8, "
                "import_hosp_n_dprefx9, "
                "import_hosp_n_dprefx10, "
                "import_hosp_n_dprefx11, "
                "import_hosp_n_dprefx12, "
                "import_hosp_n_dprefx13, "
                "import_hosp_n_dprefx14, "
                "import_hosp_n_dprefx15, "
                "import_hosp_n_dprefx16, "
                "import_hosp_n_dprefx17, "
                "import_hosp_n_dprefx18, "
                "import_hosp_n_dprefx19, "
                "import_hosp_n_dprefx20, "
                "import_hosp_n_dprefx21, "
                "import_hosp_n_dprefx22, "
                "import_hosp_n_dprefx23, "
                "import_hosp_n_dprefx24, "
                "import_hosp_n_dprefx25, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_ertime) as hospital_n_ertime, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_glasgow) as hospital_n_glasgow, "
                "import_hosp_n_iloc1, "
                "import_hosp_n_iloc2, "
                "import_hosp_n_iloc3, "
                "import_hosp_n_iloc4, "
                "import_hosp_n_iloc5, "
                "import_hosp_n_iloc6, "
                "import_hosp_n_iloc7, "
                "import_hosp_n_iloc8, "
                "import_hosp_n_iloc9, "
                "import_hosp_n_iloc10, "
                "import_hosp_n_iloc11, "
                "import_hosp_n_iloc12, "
                "import_hosp_n_iloc13, "
                "import_hosp_n_iloc14, "
                "import_hosp_n_iloc15, "
                "import_hosp_n_iloc16, "
                "import_hosp_n_iloc17, "
                "import_hosp_n_iloc18, "
                "import_hosp_n_iloc19, "
                "import_hosp_n_iloc20, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_predeldays) as hospital_n_predeldays, "
                "import_hosp_n_pretdel, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_provnumeric2) as hospital_n_provnumeric2, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_provnumeric3) as hospital_n_provnumeric3, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_provnumeric4) as hospital_n_provnumeric4, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_provnumeric5) as hospital_n_provnumeric5, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_provnumeric6) as hospital_n_provnumeric6, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_provnumeric7) as hospital_n_provnumeric7, "
                "import_hosp_n_provnumeric8, "
                "import_hosp_n_provsrv2, "
                "import_hosp_n_provsrv3, "
                "import_hosp_n_provsrv4, "
                "import_hosp_n_provsrv5, "
                "import_hosp_n_provsrv6, "
                "import_hosp_n_provsrv7, "
                "import_hosp_n_provsrv8, "
                "import_hosp_n_provtyp1, "
                "import_hosp_n_provtyp2, "
                "import_hosp_n_provtyp3, "
                "import_hosp_n_provtyp4, "
                "import_hosp_n_provtyp5, "
                "import_hosp_n_provtyp6, "
                "import_hosp_n_provtyp7, "
                "import_hosp_n_provtyp8, "
                "TO_DATE(import_hosp_n_scu1addt, 'YYYY-MM-DD') as hospital_n_scu1addt, "
                "TO_DATE(import_hosp_n_scu2addt, 'YYYY-MM-DD') as hospital_n_scu2addt, "
                "TO_DATE(import_hosp_n_scu3addt, 'YYYY-MM-DD') as hospital_n_scu3addt, "
                "TO_DATE(import_hosp_n_scu4addt, 'YYYY-MM-DD') as hospital_n_scu4addt, "
                "TO_DATE(import_hosp_n_scu5addt, 'YYYY-MM-DD') as hospital_n_scu5addt, "
                "TO_DATE(import_hosp_n_scu6addt, 'YYYY-MM-DD') as hospital_n_scu6addt, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu1adtm) as hospital_n_scu1adtm, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu2adtm) as hospital_n_scu2adtm, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu3adtm) as hospital_n_scu3adtm, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu4adtm) as hospital_n_scu4adtm, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu5adtm) as hospital_n_scu5adtm, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu6adtm) as hospital_n_scu6adtm, "
                "TO_DATE(import_hosp_n_scu1dsdt, 'YYYY-MM-DD') as hospital_n_scu1dsdt, "
                "TO_DATE(import_hosp_n_scu2dsdt, 'YYYY-MM-DD') as hospital_n_scu2dsdt, "
                "TO_DATE(import_hosp_n_scu3dsdt, 'YYYY-MM-DD') as hospital_n_scu3dsdt, "
                "TO_DATE(import_hosp_n_scu4dsdt, 'YYYY-MM-DD') as hospital_n_scu4dsdt, "
                "TO_DATE(import_hosp_n_scu5dsdt, 'YYYY-MM-DD') as hospital_n_scu5dsdt, "
                "TO_DATE(import_hosp_n_scu6dsdt, 'YYYY-MM-DD') as hospital_n_scu6dsdt, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu1dstm) as hospital_n_scu1dstm, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu2dstm) as hospital_n_scu2dstm, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu3dstm) as hospital_n_scu3dstm, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu4dstm) as hospital_n_scu4dstm, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu5dstm) as hospital_n_scu5dstm, "
                "pg_temp.TO_TIME_OR_NULL(import_hosp_n_scu6dstm) as hospital_n_scu6dstm, "
                "MAKE_INTERVAL(hours => import_hosp_n_scu1hrs::int) as hospital_n_scu1hrs, "
                "MAKE_INTERVAL(hours => import_hosp_n_scu2hrs::int) as hospital_n_scu2hrs, "
                "MAKE_INTERVAL(hours => import_hosp_n_scu3hrs::int) as hospital_n_scu3hrs, "
                "MAKE_INTERVAL(hours => import_hosp_n_scu4hrs::int) as hospital_n_scu4hrs, "
                "MAKE_INTERVAL(hours => import_hosp_n_scu5hrs::int) as hospital_n_scu5hrs, "
                "MAKE_INTERVAL(hours => import_hosp_n_scu6hrs::int) as hospital_n_scu6hrs, "
                "import_hosp_n_scu1numeric, "
                "import_hosp_n_scu2numeric, "
                "import_hosp_n_scu3numeric, "
                "import_hosp_n_scu4numeric, "
                "import_hosp_n_scu5numeric, "
                "import_hosp_n_scu6numeric, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_sculos) as hospital_n_sculos, "
                "pg_temp.TO_NUMERIC_OR_NULL(import_hosp_n_termdel) as hospital_n_termdel, "
                "study_data_year, "
                "study_version, "
                "study_sequence_number, "
                "study_id "
            "FROM import_hosp_n "
            "LIMIT 100"
        )